import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
pipeline {
  agent { label 'master' } //Agente o 'Nodes' llamado para ejecutar el codigo
  environment {
    appName = "variable" 
  }
  stages { //Fases uno puede escribir o dar tareas.

 stage("paso 1"){

      steps {
          script {			
           sh "who"
        }
      }
    }
stage("paso 2"){

      steps {
          script {			
           sh "echo 'hola mundo2'"
        }
      }
    }
  }
  post {
      always {          //Apartado que siempre ejecuta
          deleteDir()
           sh "echo 'fase always'"
      }
      success { //Apartado que solo ejecuta si termina correctamente
            sh "echo 'fase success'"
        }

      failure { //Apartado que solo ejecuta si termina incorrectamente
            sh "echo 'fase failure'"
      }

  }
}  
